name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.APP1_SSH_PRIVATEKEY }}        

      - name: Add GCE VM to known hosts
        run: ssh-keyscan -H ${{ secrets.APP1_VM_IP }} >> ~/.ssh/known_hosts

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}        

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ridwan-faturrahman
          version: 'latest'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/ridwan-faturrahman/react-repo/react-app
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build \
            --build-arg VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }} \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$IMAGE_TAG \
            . 

      - name: Push Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/ridwan-faturrahman/react-repo/react-app
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG     

      - name: Deploy to GCE VM
        run: |   
          ssh ${{ secrets.APP1_VM_USER }}@${{ secrets.APP1_VM_IP }} << 'EOF'                                         
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
            docker pull us-central1-docker.pkg.dev/ridwan-faturrahman/react-repo/react-app:latest

            docker stop react-app || true
            docker remove react-app || true   

            docker run -d \
              --name react-app \
              --restart always \
              -p 5173:80 \
              us-central1-docker.pkg.dev/ridwan-faturrahman/react-repo/react-app:latest   

            docker images -f "dangling=true" -q us-central1-docker.pkg.dev/ridwan-faturrahman/react-repo/react-app | xargs -r docker rmi
          EOF               